Repository dmalanchuk/msgFlow-AutoMsgFlow, pull requests merged in 2025-08, with the labels that each got.

#44 Feature/most processing scenario
  auth_service/tests/register_test.js
  integration_service/requirements/base.txt
  workflow_service/requirements/base.txt
  workflow_service/src/rabbitmq/broker.py
  workflow_service/src/rabbitmq/publisher.py
  workflow_service/src/rabbitmq/subscriber.py
  workflow_service/src/schemas/scenario_schema.py
  workflow_service/src/services/scenario_service.py
  workflow_service/tests/load/load_create_scen.js
Labels: feature

#49 Optimization/take out login execute action
  workflow_service/src/main.py
  workflow_service/src/rabbitmq/broker.py
  workflow_service/src/rabbitmq/publisher.py
  workflow_service/src/rabbitmq/subscriber.py
  workflow_service/src/services/execute_action.py
  workflow_service/src/services/pattern/action_service.py
Labels: optimization

#50 Doc/api
  auth_service/src/api/auth_api.py
  auth_service/src/main.py
  integration_service/src/main.py
  workflow_service/src/api/scenario_api.py
  workflow_service/src/main.py
Labels: documentation

#52 Bug/fix bot messages
  workflow_service/src/rabbitmq/subscriber.py
  workflow_service/src/redis/redis_service.py
  workflow_service/src/services/execute_action.py
  workflow_service/src/services/pattern/condition_service.py
Labels: bug, hotfix

#62 Feature/scenarios db redesign
  workflow_service/src/models/scenarios_model.py
Labels: feature
